### ISSUE TITLE
Specific Value

### ISSUE THREAD

**Issue by M-fazin** [alexmercerind/youtube-search-python#105]
How To Get A Specific Values Like Video Id Only... ?

**Comment by alexmercerind** [comment]
Traverse the returned dictionary.

**Comment by M-fazin** [comment]
> Traverse the returned dictionary.

Give me example 🤔

**Comment by raitonoberu** [comment]
@M-fazin `videoSearch.result()` returns a dictionary with one key ("result") - a list with the received videos.
```python
from youtubesearchpython import VideosSearch
videosSearch = VideosSearch("big mcthankies from mcspankies", limit = 2)
videos = videosSearch.result()["result"]
video_id = videos[0]["id"]
print(video_id)
```
