### ISSUE TITLE
await out side function

### ISSUE THREAD

**Issue by M-fazin** [alexmercerind/youtube-search-python#106]
from youtubesearchpython.__future__ import VideosSearch

videosSearch = VideosSearch('NoCopyrightSounds', limit = 2)
videosResult = await videosSearch.next()
print(videosResult)

**Comment by alexmercerind** [comment]
Please refer to the `asyncExample.py` file on the repository.

https://github.com/alexmercerind/youtube-search-python/blob/901be017ca5e71d98c89c89759ab79fbd5909aae/asyncExample.py#L199-L200

Learn more about async Python, otherwise the non ```__future__``` package also works fine I believe.
