### ISSUE TITLE
Get all videos of a channel

### ISSUE THREAD

**Issue by anshuman852** [alexmercerind/youtube-search-python#118]
Is there a way to get all channel videos of a channel by passing channel id without passing a query?
Also, thanks a lot for maintaining this project

**Comment by mytja** [comment]
This is quite possible
![channelvideos](https://user-images.githubusercontent.com/52399966/134920645-d779fee5-f636-452c-97e5-8c172cf37700.png)
As you can see you can use this:
```py
from youtubesearchpython import *

customSearch = CustomSearch('UC_aEa8K-EOJ3D6gOs7HcyNg', "EgZ2aWRlb3M%3D", limit = 1)
print(customSearch.result())
```
Because this is such a simple code, and you can quite easily use our current `CustomSearch` class, I won't create any wrapper, but will create another enum (class), with this CustomSearch parameter...

**Comment by Wojnstup** [comment]
Is there a way to fetch only the most recent videos from a channel? The method you provided above even after increasing the limit only fetches about 16 videos and they're not the most recent ones. Other than that, absolutely in love with the module!

**Comment by mytja** [comment]
> The method you provided above even after increasing the limit only fetches about 16 videos
Hmm yes, this is most likely a problem. YouTube requires a continuation key for next request and so we'd most likely have to wrapp it in its own Class...

> Is there a way to fetch only the most recent videos from a channel?
I will see... I have to get some time.

> Other than that, absolutely in love with the module!
Thanks for your support to this library. It means a lot to us (maintainers)

**Comment by anshuman852** [comment]
> Is there a way to fetch only the most recent videos from a channel? The method you provided above even after increasing the limit only fetches about 16 videos and they're not the most recent ones. Other than that, absolutely in love with the module!

Yes there is, i ended up using upload playlist of the channel and then using the PlayList function of the module. 
![image](https://user-images.githubusercontent.com/31951186/135655934-b35808f1-93f2-4dfb-98c8-2e220aba4e2c.png)
every channel has a default playlist called uploads. i get this playlist using simple requests and bs4 and then pass it to the module. the videos are sorted to upload date by default and u get 100 videos at once.

**Comment by mytja** [comment]
> > Is there a way to fetch only the most recent videos from a channel? The method you provided above even after increasing the limit only fetches about 16 videos and they're not the most recent ones. Other than that, absolutely in love with the module!
> 
> Yes there is, i ended up using upload playlist of the channel and then using the PlayList function of the module. 
> ![image](https://user-images.githubusercontent.com/31951186/135655934-b35808f1-93f2-4dfb-98c8-2e220aba4e2c.png)
> every channel has a default playlist called uploads. i get this playlist using simple requests and bs4 and then pass it to the module. the videos are sorted to upload date by default and u get 100 videos at once.

This is very interesting. There actually is an API that we can get this playlist ID from. This might be a future new class to this library.

**Comment by Wojnstup** [comment]
Thanks for the tip! What is the name of this API?

**Comment by anshuman852** [comment]
> > > Is there a way to fetch only the most recent videos from a channel? The method you provided above even after increasing the limit only fetches about 16 videos and they're not the most recent ones. Other than that, absolutely in love with the module!
> > 
> > 
> > Yes there is, i ended up using upload playlist of the channel and then using the PlayList function of the module.
> > ![image](https://user-images.githubusercontent.com/31951186/135655934-b35808f1-93f2-4dfb-98c8-2e220aba4e2c.png)
> > every channel has a default playlist called uploads. i get this playlist using simple requests and bs4 and then pass it to the module. the videos are sorted to upload date by default and u get 100 videos at once.
> 
> This is very interesting. There actually is an API that we can get this playlist ID from. This might be a future new class to this library.

there is? the youtubei api doesnt seem that documented, i found this haxx and just used it for my app lol

**Comment by mytja** [comment]
> Thanks for the tip! What is the name of this API?
> 

This API requires quite a bit of parsing (even of HTML), but it is located here: https://youtube.com/c/LinusTechTips/featured

**Comment by anshuman852** [comment]
> > Thanks for the tip! What is the name of this API?
> 
> This API requires quite a bit of parsing (even of HTML), but it is located here: https://youtube.com/c/LinusTechTips/featured
> 
> This used to probably be a &pb=1 API, but YouTube killed it off, so now we need to parse HTML, which we are already doing in some classes of this library

this is what i did, some channels have /c/Name and some have /channel/channel_id so if input was channel name i used channelsearch, got the zeroth element and got the channelid from there, and then used yt.com/channel/channel_id/videos
and get the playlist link from there

**Comment by Wojnstup** [comment]
Whenever I try to parse the page, I just get the "Accept cookies" page, what did you do to get around that?

**Comment by Zocker1999NET** [comment]
seems enough to replace the `UC`  at the beginning of the channel id with `UU` to get the uploads playlist of a channel. Tested with the first example: `UC_aEa8K-EOJ3D6gOs7HcyNg` becomes `UU_aEa8K-EOJ3D6gOs7HcyNg`.
See for yourself: [channel link](https://www.youtube.com/channel/UC_aEa8K-EOJ3D6gOs7HcyNg) and [self-generated playlist link](https://www.youtube.com/playlist?list=UU_aEa8K-EOJ3D6gOs7HcyNg)

I also tested this with some other channels and it seems to work persistent. With the generated playlist id, this tool can extract the video list as expected.

**Comment by mytja** [comment]
> seems enough to replace the `UC` at the beginning of the channel id with `UU` to get the uploads playlist of a channel. Tested with the first example: `UC_aEa8K-EOJ3D6gOs7HcyNg` becomes `UU_aEa8K-EOJ3D6gOs7HcyNg`. See for yourself: [channel link](https://www.youtube.com/channel/UC_aEa8K-EOJ3D6gOs7HcyNg) and [self-generated playlist link](https://www.youtube.com/playlist?list=UU_aEa8K-EOJ3D6gOs7HcyNg)
> 
> I also tested this with some other channels and it seems to work persistent. With the generated playlist id, this tool can extract the video list as expected.

Interesting...

According to your solution, you could get uploads this way:
```py
from youtubesearchpython import *

channel_id = "UC_aEa8K-EOJ3D6gOs7HcyNg"
channel_id = channel_id.replace("UC_", "UU_")

url = "https://www.youtube.com/playlist?list=" + channel_id

playlist = Playlist(url)

print(f'Videos Retrieved: {len(playlist.videos)}')

while playlist.hasMoreVideos:
    print('Getting more videos...')
    playlist.getNextVideos()
    print(f'Videos Retrieved: {len(playlist.videos)}')

print('Found all the videos.')
```

![snip](https://user-images.githubusercontent.com/52399966/135852125-43e656a8-2af7-4cc4-bf3e-60eea8f0b3a5.PNG)
Since there is quite a bit of request for getting channel details using this library, and our lib doesn't have this yet, I might create new `Channel` class.

Anyways, thank you @Zocker1999NET . I really appreciate your help. I will definetly mention you in some way on this library.

**Comment by JRajer** [comment]
> > seems enough to replace the `UC` at the beginning of the channel id with `UU` to get the uploads playlist of a channel. Tested with the first example: `UC_aEa8K-EOJ3D6gOs7HcyNg` becomes `UU_aEa8K-EOJ3D6gOs7HcyNg`. See for yourself: [channel link](https://www.youtube.com/channel/UC_aEa8K-EOJ3D6gOs7HcyNg) and [self-generated playlist link](https://www.youtube.com/playlist?list=UU_aEa8K-EOJ3D6gOs7HcyNg)
> > I also tested this with some other channels and it seems to work persistent. With the generated playlist id, this tool can extract the video list as expected.
> 
> Interesting...
> 
> According to your solution, you could get uploads this way:
> 
> ```python
> from youtubesearchpython import *
> 
> channel_id = "UC_aEa8K-EOJ3D6gOs7HcyNg"
> channel_id = channel_id.replace("UC_", "UU_")
> 
> url = "https://www.youtube.com/playlist?list=" + channel_id
> 
> playlist = Playlist(url)
> 
> print(f'Videos Retrieved: {len(playlist.videos)}')
> 
> while playlist.hasMoreVideos:
>     print('Getting more videos...')
>     playlist.getNextVideos()
>     print(f'Videos Retrieved: {len(playlist.videos)}')
> 
> print('Found all the videos.')
> ```
> 
> ![snip](https://user-images.githubusercontent.com/52399966/135852125-43e656a8-2af7-4cc4-bf3e-60eea8f0b3a5.PNG) Since there is quite a bit of request for getting channel details using this library, and our lib doesn't have this yet, I might create new `Channel` class.
> 
> Anyways, thank you @Zocker1999NET . I really appreciate your help. I will definetly mention you in some way on this library.

Since not all channels contain underscore at the end of "UC", I'd that line like:
`list_id = "UU" + channel_id.lstrip("UC")`
