### ISSUE TITLE
Add proxy option

### ISSUE THREAD

**Issue by ricardofunke** [alexmercerind/youtube-search-python#119]
I miss a proxy option for this tool so that we can pass a proxy URL like we do with the youtube-dl tool.

Is it possible to use youtube-search-python through a proxy even without such option? I was trying something like that:

```
    {...}
        http_proxy = f"http://{set_proxy()}"
        os.environ['HTTP_PROXY'] = http_proxy
        os.environ['http_proxy'] = http_proxy
        orig_get = requests.get
        proxies = {
            'http': http_proxy,
        }
        requests.get = partial(orig_get, proxies=proxies)

    try:
        videosSearch = CustomSearch(query=query,
                                    region=region,
                                    language=language,
                                    searchPreferences=set_search_pref(),
                                    limit=limit*2)
    {...}
```

**Comment by mytja** [comment]
#63
This feature has already been proposed.
What is also fascinating about your example is that it doesnt proxy anything.
I can see you are using `requests` package for proxying, and this would probably work if we'd be using it. We aren't dependend on requests package nor we are using it.

**Comment by ricardofunke** [comment]
Oh cool, sorry for this post then and thanks for the clarification about my "solution". 
Best! ;)

**Comment by CodeGodz** [comment]
@mytja sounds amazing! Could you provide a code example of how we have to set up the proxy to use it with youtube-search?

**Comment by wanghaisheng** [comment]
how about socks5://127.0.0.1:1080 @mytja
