### ISSUE TITLE
How get the search result in proper format as csv ?

### ISSUE THREAD

**Issue by bt400** [alexmercerind/youtube-search-python#131]
Hello, thank you for the code,
I am new to python, it took me a lot to figure out how to use this, unfortunately, there is no simple instruction on how to use it, anyhow, I pasted some of the codes from the example file into a file and name it "test .py",  and run it,
unless there is another way to use it, if so please tell me.

when running the test.py file, the result that shows on-screen ( I use VS code) is in JSON format, I could not convert it into a CSV file, I tested the JSON content on [Here](https://jsonlint.com/) a JSON code verifier, and it does not verify it, it gives me errors.
I am trying to use the search function of suggestion keywords:
`suggestions = await Suggestions.get('luxury lifestyle', language = 'en', region = 'US')
    print(suggestions)`

is there anywhere to solve this problem, please?
how do you guys get the result in proper format?
Thanks.

**Comment by mytja** [comment]
I hope this answers your questions #133

**Comment by mytja** [comment]
Closing due to no response
