### ISSUE TITLE
Example code to retrieve playlist items from bigger playlists stopped working

### ISSUE THREAD

**Issue by Zocker1999NET** [alexmercerind/youtube-search-python#135]
see code from README:
```python
from youtubesearchpython import *

playlist = Playlist('https://www.youtube.com/playlist?list=PLRBp0Fe2GpgmsW46rJyudVFlY6IYjFBIK')

print(f'Videos Retrieved: {len(playlist.videos)}')

while playlist.hasMoreVideos:
    print('Getting more videos...')
    playlist.getNextVideos()
    print(f'Videos Retrieved: {len(playlist.videos)}')

print('Found all the videos.')
```

Code exists with following error first:
```
Traceback (most recent call last):
  File "*/test.py", line 8, in <module>
    playlist = Playlist(uri)
  File "*/venv/lib/python3.9/site-packages/youtubesearchpython/extras.py", line 561, in __init__
    self.info = copy.deepcopy(self.__playlist.result)
NameError: name 'copy' is not defined
```

For this just a `import copy` seemed to be missing, I will append a PR fixing this.
However it still does not work due to the following error:
```
Traceback (most recent call last):
  File "*/test.py", line 11, in <module>
    pl.getNextVideos()
  File "*/venv/lib/python3.9/site-packages/youtubesearchpython/extras.py", line 571, in getNextVideos
    self.__playlist.next()
AttributeError: 'PlaylistCore' object has no attribute 'next'
```

PlaylistCore has no `next()` method, however has a `_next()` method, but just calling that does not work either. For further fixing I'm missing some insight into this code base. It would be great if someone could fix that.

Anyway thanks for maintaining this code base! Since I know it, it became quite important for my own projects.

**Comment by mytja** [comment]
I have fixed getting more videos.
I will now release a new release, as this patches are quite important. Migration to Core classes messed quite a lot of things up. Thanks for spotting

**Comment by mytja** [comment]
Here we go. It is now released. I am really thankful for your contributions.
