### ISSUE TITLE
Fix post() got an unexpected keyword argument 'proxies' in pypi also

### ISSUE THREAD

**Issue by Hunter-XDD** [alexmercerind/youtube-search-python#140]
Please this issue post() got an unexpected keyword argument 'proxies'
In pypi also

**Comment by mytja** [comment]
#139 Many people seem to have this error. You have too old version of httpx installed and this PR should fix it.
Current release on PyPi doesn't contain this fix, so please use latest release from Git:
```
pip install git+https://github.com/alexmercerind/youtube-search-python
```
