### ISSUE TITLE
[Feature Request] VideosSearch - enable search by channel ID

### ISSUE THREAD

**Issue by taewookim** [alexmercerind/youtube-search-python#141]
i.e. 
VideosSearch("https://www.youtube.com/c/XYZ")

or 

VideosSearch("https://www.youtube.com/channel/XYZBLAHBLAH)

**Comment by mytja** [comment]
Searching for videos in channel: https://github.com/alexmercerind/youtube-search-python#getting-videos-and-playlists-in-specific-channel
Getting all videos of a channel: https://github.com/alexmercerind/youtube-search-python/issues/118#issuecomment-933445260
Searching for channels: https://github.com/alexmercerind/youtube-search-python#search-for-only-channels

Did you mean any of it?

**Comment by mytja** [comment]
Closing due to no response.
