### ISSUE TITLE
'CustomSearch' object has no attribute 'next'

### ISSUE THREAD

**Issue by ricardofunke** [alexmercerind/youtube-search-python#146]
Since last update to version 1.5.2 the CustomSearch object doesn't recognize the next method anymore. Is that a bug or should I do something else to get the next pages of custom searches?

**Comment by mytja** [comment]
Yeah, i see where the problem is. I'll fix it.

**Comment by mytja** [comment]
This should fix your problem, please test it with `pip install git+https://github.com/alexmercerind/youtube-search-python`
