### ISSUE TITLE
Retrieving rich (.webp) thumbnails for a single video

### ISSUE THREAD

**Issue by tonycpsu** [alexmercerind/youtube-search-python#147]
I discovered this module while looking for a way to retrieve animated `.webp` thumbnails in my application, but I can't find a way to do it just for a single video.  I see there is an `extras.Video` class where you can get the information for a single video by ID, but the `richThumbnail` attribute doesn't come back for those.

The only way I can get it to work is to do a `Search` for that video ID that can return many results and check the video ID of each result for the one I want, like this:
```python
        search = Search(video_id).result()
        thumbnail = next(
            (
                s["richThumbnail"]
                for s in search["result"]
                if s["id"] == video_id
            ),
            None
        )
```

However, I don't know that it's guaranteed that searching by video ID always retrieves the video in question, and it seems wasteful to have to do this when there's already a method to get info for a single ID.

Is there a reason the search for a single video ID doesn't get the same information that search results do?  Is there a way to include richThumbnail for the `Video.get()` method?

**Comment by mytja** [comment]
Hello!
I've been digging into this and it seems like we cannot get rich thumbnails using Video.get() endpoint, as YouTube only provides them at search (let's be honest, did you see them when you already loaded the video - i don't think so).
About that search question - YouTube doesn't have a perfect algorithm that would always detect your video. In case it doesn't sense it, I'd do a while loop or some recursion.
I know it's wasteful, but that's something I sadly can't fix.
Hope you understand.
Have a nice Christmas and a happy new year
