### ISSUE TITLE
Do you can set title with Unicode

### ISSUE THREAD

**Issue by hoan277** [alexmercerind/youtube-search-python#15]
Hello
With title is Vietnamese, Chinese, Japanese --> title output is not support utf8 unicode right now.
so you can add this in next version please. Thank you so much

**Comment by alexmercerind** [comment]
Hi @hoan277 !

Thankyou for your information.
I recommend you to take a look at issue thread #5. 

You need to manually decode the strings if you choose mode="json" (JSON does not store them like that.)

** Please try using mode="dict" or mode="list". **

Let me know if issue still persists.

Feel free to reopen issue.
