### ISSUE TITLE
Get video publish time from playlist

### ISSUE THREAD

**Issue by bralbral** [alexmercerind/youtube-search-python#151]
Hello. I want to retrieve all videos from channel, and use your example:

```
from youtubesearchpython import *

channel_id = "UC_aEa8K-EOJ3D6gOs7HcyNg"
playlist = Playlist(playlist_from_channel_id(channel_id))

print(f'Videos Retrieved: {len(playlist.videos)}')

while playlist.hasMoreVideos:
    print('Getting more videos...')
    playlist.getNextVideos()
    print(f'Videos Retrieved: {len(playlist.videos)}')

print('Found all the videos.')

```
But how can i get publish time?

This information exists in `video -> accessibility -> title`
![image](https://user-images.githubusercontent.com/54455457/148093457-24b8f1f3-7ddd-455b-9caa-122675a0b442.png)
Is it right way get it from title, or can you add new element `publish_time` in video dict ?

**Comment by mytja** [comment]
There sadly is no way of getting it directly from playlist, except if you parse it. However I certanly wouldn't recommend it, as it's quite painful, and we don't know if it appears on all videos (it probably does).

So, instead I'd recommend this:
```py
from youtubesearchpython import *

channel_id = "UC_aEa8K-EOJ3D6gOs7HcyNg"
playlist = Playlist(playlist_from_channel_id(channel_id))

video = playlist.videos[0]

v = Video.getInfo(video["id"])
print(v["publishDate"])
```

Let me know if you meant something else.
Closing the issue
