### ISSUE TITLE
Searching channel using it's ID

### ISSUE THREAD

**Issue by MrPotato374** [alexmercerind/youtube-search-python#153]
Well, currently we can only search Youtube channels through their names. It'll be cool if we're able to search the channel through it's ID which will make it easier to find the channel we want. As there are bigger Youtubers that have their own **CUSTOM CHANNEL ID** maybe you can make it search for it!
And this way, it will find it more accurately!

**Comment by mytja** [comment]
YouTube doesn't support this, thus we cannot implement it. You can always use [ChannelsSearch](https://github.com/alexmercerind/youtube-search-python#search-for-only-channels) class to search for its ID.
