### ISSUE TITLE
Playlist.getNextVideos() error

### ISSUE THREAD

**Issue by dscrofts** [alexmercerind/youtube-search-python#157]
Hi,

I was testing out the above method on long playlists (3000+ videos) and noticed that it fails sometimes. Example:

```
from youtubesearchpython import *

playlist = Playlist("https://www.youtube.com/playlist?list=PLpR68gbIfkKmrNp3yeVmZRyNR_Lb6XM5Q")

while playlist.hasMoreVideos:
    playlist.getNextVideos()

print(len(playlist.videos))
```

Gives the error:
```
Traceback (most recent call last):
  File "/Users/dan/Google Drive/Programming/ytp/test.py", line 43, in <module>
    playlist.getNextVideos()
  File "/usr/local/lib/python3.10/site-packages/youtubesearchpython/extras.py", line 574, in getNextVideos
    self.__playlist._next()
  File "/usr/local/lib/python3.10/site-packages/youtubesearchpython/core/playlist.py", line 68, in _next
    self.next_post_processing()
  File "/usr/local/lib/python3.10/site-packages/youtubesearchpython/core/playlist.py", line 56, in next_post_processing
    self.__getNextComponents()
  File "/usr/local/lib/python3.10/site-packages/youtubesearchpython/core/playlist.py", line 191, in __getNextComponents
    for videoElement in continuationElements:
TypeError: 'NoneType' object is not iterable
```

However the following playlist URLs do work:
`https://www.youtube.com/playlist?list=PLXFwTY00FRUUZzL_Vjhy-bE8WIao3eyOi` (3000+ videos)
`https://www.youtube.com/playlist?list=PLI_eFW8NAFzYAXZ5DrU6E6mQ_XfhaLBUX` (4000+ videos)
`https://www.youtube.com/playlist?list=PLT3qfwQPY9r7p5CIQWKG1qmcaqoU4nHvV` (4000+ videos)

**Comment by poohzaza166** [comment]
wait it worked for you guys mines dose nothing and just get the first 100 video for temporary workaround just use this library since this one work for me https://pypi.org/project/scrapetube/  and it well docoumented

**Comment by mytja** [comment]
> wait it worked for you guys mines dose nothing and just get the first 100 video for temporary workaround just use this library since this one work for me https://pypi.org/project/scrapetube/  and it well docoumented   

Does it give you any error? Did you run `playlist.getNextVideos()`? Is Playlist more than 100 videos long?

**Comment by poohzaza166** [comment]
no it just dose nothing

**Comment by mytja** [comment]
Can I maybe get a Playlist link?

**Comment by dscrofts** [comment]
> > wait it worked for you guys mines dose nothing and just get the first 100 video for temporary workaround just use this library since this one work for me https://pypi.org/project/scrapetube/  and it well docoumented
> 
> Does it give you any error? Did you run `playlist.getNextVideos()`? Is Playlist more than 100 videos long?
> 
> Btw, @dscrofts , thanks for your extensive reports. It really helps me. I appreciate it.

Thanks for all your hard work on this project @mytja . Sadly I don't have the expertise to provide a fix for the issue, but happy to keep testing things out!

**Comment by poohzaza166** [comment]
> Can I maybe get a Playlist link?

ok https://youtube.com/playlist?list=PLSJh9S2IPebGSSqkXACtbCJJcYc26Iy3i

**Comment by mytja** [comment]
@dscrofts 
Your issue is pretty strange. It seems to be something with YouTube backend, not with this library, so sadly I cannot fix it.
You can see here that I scrolled down to 3347th video. After that it stops and I get an infinite scroller and a 200 OK response from API. Same on this library.
![image](https://user-images.githubusercontent.com/52399966/151606699-fc9cb29d-197a-4ea8-b503-932fa4091c2b.png)

What I get as a response on this library is this (all the unimportant bloat was removed):
```json
{
   "contents":{
      "twoColumnBrowseResultsRenderer":{
         "tabs":[
            {
               "tabRenderer":{
                  "selected":true,
                  "content":{
                     "sectionListRenderer":{
                        "contents":[
                           {
                              "itemSectionRenderer":{
                                 "contents":[
                                    {
                                       "messageRenderer":{
                                          "text":{
                                             "simpleText":"Unavailable videos are hidden"
                                          },
                                          "trackingParams":"CBAQljsYACITCKTlqbqR1fUCFRk04Aod8G4JKw==",
                                          "button":{
                                             "buttonRenderer":{
                                                "style":"STYLE_DEFAULT",
                                                "size":"SIZE_DEFAULT",
                                                "isDisabled":false,
                                                "icon":{
                                                   "iconType":"CLOSE"
                                                },
                                                "trackingParams":"CBEQ8FsiEwik5am6kdX1AhUZNOAKHfBuCSs=",
                                                "accessibilityData":{
                                                   "accessibilityData":{
                                                      "label":"Dismiss"
                                                   }
                                                },
                                                "command":{
                                                   "clickTrackingParams":"CBEQ8FsiEwik5am6kdX1AhUZNOAKHfBuCSs=",
                                                   "hideEnclosingAction":{
                                                      "hack":true
                                                   }
                                                }
                                             }
                                          },
                                          "style":{
                                             "value":"RENDER_STYLE_BANNER"
                                          }
                                       }
                                    },
                                    {
                                       "messageRenderer":{
                                          "text":{
                                             "runs":[
                                                {
                                                   "text":"No videos in this playlist yet"
                                                }
                                             ]
                                          },
                                          "trackingParams":"CA8QljsYASITCKTlqbqR1fUCFRk04Aod8G4JKw=="
                                       }
                                    }
                                 ],
                                 "trackingParams":"CA4Quy8YACITCKTlqbqR1fUCFRk04Aod8G4JKw=="
                              }
                           }
                        ],
                        "trackingParams":"CA0Qui8iEwik5am6kdX1AhUZNOAKHfBuCSs="
                     }
                  },
                  "trackingParams":"CAwQ8JMBGAciEwik5am6kdX1AhUZNOAKHfBuCSs="
               }
            }
         ]
      }
   }
}
```

You can see `Unavailable videos are hidden` and no other response.
Following is my guess:
- Channel has some unavailable videos, which YouTube's API doesn't want to send, so it says, the playlist has 3,793 videos, meanwhile it has only 3,347 videos, others are hidden (because they are unavailable - the poster most likely deleted them).

This is most likely an issue with YouTube backend itself, so I cannot do anything about it. Why doesn't this occour on other Playlists with unavailable playlists, I don't know, it might be just purely the size of this Playlist and incorrect parsing on internal server.

The only thing I can do is to hide this issue (fix, that it doesn't throw an error anymore), other things I sadly cannot do.

I wish I could've helped you.

Thanks for all of your extensive reports. :heart:
I will mention you and other contributors in the README.

---

@poohzaza166 
I can retrieve this Playlist without any problems. Though I am on development branch and currently am patching some stuff. If it didn't work before, I'd recommend you to try again after a few days, when patches are going to be deployed to PyPi.

I have to ask you something. Do you have poor internet connection and it takes forever to get all those videos? Does your government block YouTube or other Google services?

I used following code:
```py
from youtubesearchpython import *

playlist = Playlist("https://youtube.com/playlist?list=PLSJh9S2IPebGSSqkXACtbCJJcYc26Iy3i")

while playlist.hasMoreVideos:
    print(len(playlist.videos))
    playlist.getNextVideos()

print(len(playlist.videos))
```

And following is the response:
```
100
200
300
400
500
600
700
800
900
1000
1100
1200
1222
```

**Comment by mytja** [comment]
Package has been published to PyPi. Please upgrade to latest version using `pip install youtube-search-python --upgrade`

Happy YouTube searching, everyone.

**Comment by poohzaza166** [comment]
I have to ask you something. Do you have poor internet connection and it takes forever to get all those videos? Does your government block YouTube or other Google services?

um i have a gigabit fiber and no as far as i am aware thailand goverment don't block youtube service yet 

my problem with getting video from playlist is i can only get the first 100 video and the loop don't progess futher but that was like in october 2021 and i haven't update or check the libary since then and also a side libary that i am using is pycord will that cause any conflict?  and i am currently using this  https://pypi.org/project/scrapetube/  and i think you could checkout how they parse their respond to help with this and also i will try updating youtube-search-python thanks for your help

> Hello! Here are results from my investigation.
> 
> @dscrofts Your issue is pretty strange. It seems to be something with YouTube backend, not with this library, so sadly I cannot fix it. You can see here that I scrolled down to 3347th video. After that it stops and I get an infinite scroller and a 200 OK response from API. Same on this library. ![image](https://user-images.githubusercontent.com/52399966/151606699-fc9cb29d-197a-4ea8-b503-932fa4091c2b.png)
> 
> What I get as a response on this library is this (all the unimportant bloat was removed):
> 
> ```json
> {
>    "contents":{
>       "twoColumnBrowseResultsRenderer":{
>          "tabs":[
>             {
>                "tabRenderer":{
>                   "selected":true,
>                   "content":{
>                      "sectionListRenderer":{
>                         "contents":[
>                            {
>                               "itemSectionRenderer":{
>                                  "contents":[
>                                     {
>                                        "messageRenderer":{
>                                           "text":{
>                                              "simpleText":"Unavailable videos are hidden"
>                                           },
>                                           "trackingParams":"CBAQljsYACITCKTlqbqR1fUCFRk04Aod8G4JKw==",
>                                           "button":{
>                                              "buttonRenderer":{
>                                                 "style":"STYLE_DEFAULT",
>                                                 "size":"SIZE_DEFAULT",
>                                                 "isDisabled":false,
>                                                 "icon":{
>                                                    "iconType":"CLOSE"
>                                                 },
>                                                 "trackingParams":"CBEQ8FsiEwik5am6kdX1AhUZNOAKHfBuCSs=",
>                                                 "accessibilityData":{
>                                                    "accessibilityData":{
>                                                       "label":"Dismiss"
>                                                    }
>                                                 },
>                                                 "command":{
>                                                    "clickTrackingParams":"CBEQ8FsiEwik5am6kdX1AhUZNOAKHfBuCSs=",
>                                                    "hideEnclosingAction":{
>                                                       "hack":true
>                                                    }
>                                                 }
>                                              }
>                                           },
>                                           "style":{
>                                              "value":"RENDER_STYLE_BANNER"
>                                           }
>                                        }
>                                     },
>                                     {
>                                        "messageRenderer":{
>                                           "text":{
>                                              "runs":[
>                                                 {
>                                                    "text":"No videos in this playlist yet"
>                                                 }
>                                              ]
>                                           },
>                                           "trackingParams":"CA8QljsYASITCKTlqbqR1fUCFRk04Aod8G4JKw=="
>                                        }
>                                     }
>                                  ],
>                                  "trackingParams":"CA4Quy8YACITCKTlqbqR1fUCFRk04Aod8G4JKw=="
>                               }
>                            }
>                         ],
>                         "trackingParams":"CA0Qui8iEwik5am6kdX1AhUZNOAKHfBuCSs="
>                      }
>                   },
>                   "trackingParams":"CAwQ8JMBGAciEwik5am6kdX1AhUZNOAKHfBuCSs="
>                }
>             }
>          ]
>       }
>    }
> }
> ```
> 
> You can see `Unavailable videos are hidden` and no other response. Following is my guess:
> 
>     * Channel has some unavailable videos, which YouTube's API doesn't want to send, so it says, the playlist has 3,793 videos, meanwhile it has only 3,347 videos, others are hidden (because they are unavailable - the poster most likely deleted them).
> 
> 
> This is most likely an issue with YouTube backend itself, so I cannot do anything about it. Why doesn't this occour on other Playlists with unavailable playlists, I don't know, it might be just purely the size of this Playlist and incorrect parsing on internal server.
> 
> The only thing I can do is to hide this issue (fix, that it doesn't throw an error anymore), other things I sadly cannot do.
> 
> I wish I could've helped you.
> 
> Thanks for all of your extensive reports. heart I will mention you and other contributors in the README.
> 
> @poohzaza166 I can retrieve this Playlist without any problems. Though I am on development branch and currently am patching some stuff. If it didn't work before, I'd recommend you to try again after a few days, when patches are going to be deployed to PyPi.
> 
> I have to ask you something. Do you have poor internet connection and it takes forever to get all those videos? Does your government block YouTube or other Google services?
> 
> I used following code:
> 
> ```python
> from youtubesearchpython import *
> 
> playlist = Playlist("https://youtube.com/playlist?list=PLSJh9S2IPebGSSqkXACtbCJJcYc26Iy3i")
> 
> while playlist.hasMoreVideos:
>     print(len(playlist.videos))
>     playlist.getNextVideos()
> 
> print(len(playlist.videos))
> ```
> 
> And following is the response:
> 
> ```
> 100
> 200
> 300
> 400
> 500
> 600
> 700
> 800
> 900
> 1000
> 1100
> 1200
> 1222
> ```

**Comment by mytja** [comment]
We are using YouTube's Internal API and that should work. I had a look at scrapetube, and it uses same methods as we do, so I don't think this is an error. Indeed, we used to have many many issues with Playlist class, but now it's far more stable and faster than anytime before.

> haven't update or check the libary since then and also a side libary that i am using is pycord will that cause any conflict
About that incompatibility, I don't really know. It should be compatible, as I can import both libraries at the same time.

Please try to upgrade the library using `pip install youtube-search-python --upgrade`

**Comment by poohzaza166** [comment]
thanks for your support
