### ISSUE TITLE
SearchVideos function failed today

### ISSUE THREAD

**Issue by brian7685** [alexmercerind/youtube-search-python#16]
SearchVideos returns nothing right now.

**Comment by alexmercerind** [comment]
I appreciate your feedback!

I'm also able to reproduce the bug. You can expect the bugfix within 24 hours.
YouTube likes to change the stuff a lot.

Thankyou!

**Comment by alexmercerind** [comment]
🎉 alexmercerind@cdfd4ff16ef45a00c448983586b4fcc7cd8ef123

Install latest release from PyPI with 

```
pip3 install youtube-search-python==1.2.7
```

It should fix the issue. Let me know...

Closing the issue!

**Comment by Gopyc** [comment]
Hey alex,

SearchVideos returns nothing.

{
    "search_result": []
}

**Comment by alexmercerind** [comment]
@Gopyc 
Please assure that you are using the latest version v1.2.7
For me, it is working fine.

Thankyou!
Let me know if issue persists.

**Comment by Gopyc** [comment]
> @Gopyc
> Please assure that you are using the latest version v1.2.7
> For me, it is working fine.
> 
> Thankyou!
> Let me know if issue persists.

I've updated to 1.2.7 and it works. Thx
