### ISSUE TITLE
Retrieve channel info & search with a specific time span

### ISSUE THREAD

**Issue by nghuyong** [alexmercerind/youtube-search-python#164]
Thank you for this really great work!!!
I have a question, how can I search videos with keywords in a specific time span. 
For example, I want to get the videos with "china" and  uploading between 2022.1.1 - 2022.1.30

**Comment by mytja** [comment]
Hello,
I think that's not possible
![image](https://user-images.githubusercontent.com/52399966/157832453-a89b7b8c-f533-406d-9eaf-5e46e27ba8b2.png)
These are all of filters that are available in YouTube.

But we do provide [filters](https://github.com/alexmercerind/youtube-search-python/blob/main/youtubesearchpython/core/constants.py#L51-L56) for last month, last hour, last day etc.
```py
from youtubesearchpython import *

customSearch = CustomSearch('NoCopyrightSounds', VideoUploadDateFilter.lastHour, limit = 1)

print(customSearch.result())
```

I don't know if you are able to search in any third party app by the timespan, if you do know any app, please let me know and I will have a look at it.

**Comment by nghuyong** [comment]
Thank you for the reply!!! Currently, I don't find an app that can search with a timespan.
I still have a question, How can I get the information of a user? for example:  https://www.youtube.com/c/NoCopyrightSounds/about

**Comment by mytja** [comment]
> Thank you for the reply!!! Currently, I don't find an app that can search with a timespan. I still have a question, How can I get the information of a user? for example: https://www.youtube.com/c/NoCopyrightSounds/about

This is currently not possible. Will have a look into that.

**Comment by nghuyong** [comment]
👍👍👍

**Comment by mytja** [comment]
Sorry it takes me so long. I have a lot of other projects. Will have a look soon.

**Comment by nghuyong** [comment]
Never mind, Thanks a lot!!!

**Comment by mytja** [comment]
When I merge #165, I'll publish everything onto PyPi and you are ready to go.
If you are curious how does it look like, I'd recommend installing from Git:
```
pip install git+https://github.com/alexmercerind/youtube-search-python@transcript
```
You can use following code:
```py
from youtubesearchpython import Channel

print(Channel.get("UC_aEa8K-EOJ3D6gOs7HcyNg"))
```

**Comment by nghuyong** [comment]
wow!!! nice job!
