### ISSUE TITLE
Errors on Video.getInfo

### ISSUE THREAD

**Issue by kechinvv** [alexmercerind/youtube-search-python#167]
Hello! Firstly, thanks for your lib, it's very useful. But I am faced with getting this errors (1 or 2 pic at differnt times). I'm going through all the users' videos and trying to get information about the video for a long time.  A few hours later I get errors in getInfo. At first I thought I got banned, but immediately after restarting everything works. It's not critical, but I have to keep an eye on it or try catch an error without knowing its causes. Sample of my code:
```
playlist = Playlist(playlist_from_channel_id(channel['id']))
for vid in playlist.videos:
        views += int(Video.getInfo(vid['link'])['viewCount']['text'])
    while playlist.hasMoreVideos:
        playlist.getNextVideos()
        for vid in playlist.videos:
            views += int(Video.getInfo(vid['link'])['viewCount']['text'])
```
I use it with 
```
pip install git+...
```
![photo_2022-03-26_15-02-35](https://user-images.githubusercontent.com/54941182/160237218-9f0550ec-a3e0-4fc9-8148-958dc79957f1.jpg)
or
![photo_2022-03-26_15-00-35](https://user-images.githubusercontent.com/54941182/160237219-32e1e46b-c20f-4d66-b3e2-62c7d8541c50.jpg)

**Comment by mytja** [comment]
Hello,
this is certainly weird. Maybe YouTube was unable to process your request that one time. It's definetly hard to reproduce and best way to solve issues is definetly with `try` and `except`.
I cannot help you much about it, as I cannot reproduce it, so I wish you best luck on your project.

**Comment by kechinvv** [comment]
Thanks for your reply! I am use `try except` and it helps. The loss of one request is not critical for me.
