### ISSUE TITLE
Support for Python 2

### ISSUE THREAD

**Issue by mytja** [alexmercerind/youtube-search-python#17]
Hello!
I'm working on a project that would need your library since YouTube is making a lot of changes this month, which caused non working of my code. Saw same issue with your code a couple of days ago (#16 ) but you resolved it.
However this library is designed for Python 3. Is it somehow possible to integrate Python 2 into your library. If not, i will move my project to Python 3, since I want to do it for quite of while and this would be a big plus for movement.
Project site: https://github.com/mytja/MyAssistantOS-Raspbian
Thank you so much
mytja

**Comment by alexmercerind** [comment]
Hi @mytja !

I understand your issue. I'm happy that you looked this library, I liked your project aswell.
I can definitely try adding python 2 support for this project and it won't be a big rewrite I believe and things like urllib2 already exist in python2, so it can be easy.
I cannot guarantee that I'll be able to, or give any approximate duration. (Though I'm pretty sure you can expect it soon merged into master.)

Thankyou 😃!

**Comment by mytja** [comment]
Hello!
Thank you so much. I will move my project (or at least try) to Python 3 anyways, since almost all of my libraries are unsupported currently. However I think it would be very useful to others.
I looked a little on your code.
So I saw one thing that you have to change to move to Python 2.
import urllib.requests
urllib.requests.____(___)

Both of those lines must be changed to this, since Python2 doesn't have urllib._____, only urllib

import urllib
urllib.____(___)

___ represents your commands.
Hope this helps
MyTja Team

**Comment by alexmercerind** [comment]
Hello @mytja !
Thanks a lot for your help. I made some commits in the branch [python2](https://github.com/alexmercerind/youtube-search-python/tree/python2) ... 

The module is working fine for me now, in Python 2. Try running "Usage Example.py" in your Python 2 environment, I believe it will work just fine. 
Thank you for looking at my code (I'm a newbie, I added a lot comments for people to read)... This project is not taking help of any other third party library like BeautifulSoup (for parsing or web scraping) or even requests, it is made in pure vanilla python. 
 So I try to do my best for keeping it working/up-to-date time to time.

Thanks a lot 😃!
Closing the issue, let me know how it goes.

**Comment by alexmercerind** [comment]
Try installing using 

```
pip2 install youtube-search-python
```

Should work just fine!

**Comment by mytja** [comment]
Python 2 doesn't use "pip2", it's only "pip".
I will test your library proboably tomorrow.
Thank you so much
mytja

**Comment by alexmercerind** [comment]
```pip2``` works for me somehow...

**Comment by mytja** [comment]
This modification is fully working!
It is possible, that pip2 somehow exists, but I don't know ;-)
I'm very satisfied with your library!
Thank you so much for your work!
Now it's time for me to help you (#18 ) and to work on my project! :-)
