### ISSUE TITLE
Filter livestreams

### ISSUE THREAD

**Issue by Bluepengie** [alexmercerind/youtube-search-python#171]
Could you add a way to filter whether a search returns a livestream or not? When searching, I don't want any livestream results.

**Comment by dscrofts** [comment]
Livestream results don't have a duration, so you can filter the results as follows:

```python
from youtubesearchpython import *

search = VideosSearch("whatever")
results = search.result()["result"]

results_without_livestreams = [r for r in results if r["duration"]]
```

**Comment by Bluepengie** [comment]
Works perfect. Thanks!

**Comment by mytja** [comment]
We've recently added `livestream` filter:
https://github.com/alexmercerind/youtube-search-python/pull/168

You can use it within `CustomSearch` by using `SearchMode.livestreams` as a filter. I haven't tested this myself, if it doesn't work, please comment here.

**Comment by dscrofts** [comment]
> We've recently added `livestream` filter: #168
> 
> You can use it within `CustomSearch` by using `SearchMode.livestreams` as a filter. I haven't tested this myself, if it doesn't work, please comment here.

@mytja I tested it out and it seems to be working great. However it doesn't appear there is a way to issue a query and _exclude_ live streams from the (video) result set. I can't find a way to do this through the regular YouTube interface anyway, and some Googling shows that people recommend filtering out results manually, e.g. [YouTube Data API: Exclude livestreams from Search.list result set](https://stackoverflow.com/questions/66068899/youtube-data-api-exclude-livestreams-from-search-list-result-set).

**Comment by mytja** [comment]
> I tested it out and it seems to be working great

So glad it's working for you. :blue_heart: 

> I can't find a way to do this through the regular YouTube interface anyway

If it isn't available in YouTube web app, we sadly cannot do anything...
