### ISSUE TITLE
about video information retrieved, miss "how many likes/dislike" properties

### ISSUE THREAD

**Issue by cosimopp** [alexmercerind/youtube-search-python#173]

**Comment by mytja** [comment]
YouTube has removed the dislike button, thus we can no longer retrieve ratio between likes and dislikes. You can use [Return YouTube Dislikes](https://returnyoutubedislikeapi.com/swagger/index.html) project and its awesome API. Have a look at GET request for `/Votes`. We cannot provide anything more.
