### ISSUE TITLE
[Feature Request] get list of Playlists created by a user

### ISSUE THREAD

**Issue by iamtalhaasghar** [alexmercerind/youtube-search-python#174]
![image](https://user-images.githubusercontent.com/46928648/165131024-362fb08c-25ec-441b-9aa8-bdc8f5b6e604.png)

This would be an awesome feature to have in `youtube-search-python`.

**Comment by mytja** [comment]
You can now use `Channel` class for that, thanks to @fabi321 
```py
from youtubesearchpython import Channel

channel = Channel("UC_aEa8K-EOJ3D6gOs7HcyNg")
print(len(channel.result["playlists"]))
while channel.has_more_playlists():
    channel.next()
    print(len(channel.result["playlists"]))
```
