### ISSUE TITLE
Transcriptions are blank

### ISSUE THREAD

**Issue by kubicndmr** [alexmercerind/youtube-search-python#181]
Hello, 

I'm trying to reproduce the transcription example 

```
from youtubesearchpython import Transcript

url = "https://www.youtube.com/watch?v=-1xu0IP35FI"

transcript_en = Transcript.get(url)
# you actually don't have to pass a valid URL in following Transcript call. You can input an empty string, but I do recommend still inputing a valid URL.
transcript_2 = Transcript.get(url, transcript_en["languages"][-1]["params"]) # in my case, it'd output Spanish.
print(transcript_2)
```

However, I'm getting none values in text fields instead. My output is like this: 
```{'segments': [{'startMs': '210', 'endMs': '2129', 'text': None, 'startTime': '0:00'}, {'startMs': '2130', 'endMs': '3670', 'text': None, 'startTime': '0:02'}, {'startMs': '3670', 'endMs': '4940', 'text': None, 'startTime': '0:03'}, {'startMs': '4940', 'endMs': '7610', 'text': None, 'startTime': '0:04'}, {'startMs': '7610', 'endMs': '10760', 'text': None, 'startTime': '0:07'}, {'startMs': '10760', 'endMs': '11593', 'text': None, 'startTime': '0:10'}, {'startMs': '11593', 'endMs': '14230', 'text': None, 'startTime': '0:11'}, {'startMs': '14230', 'endMs': '16349', 'text': None, 'startTime': '0:14'}, {'startMs': '16350', 'endMs': '17760', 'text': None, 'startTime': '0:16'}, {'startMs': '17760', 'endMs': '19300', 'text': None, 'startTime': '0:17'}, {'startMs': '19300', 'endMs': '20869', 'text': None, 'startTime': '0:19'}, {'startMs': '20870', 'endMs': '24280', 'text': None, 'startTime': '0:20'}, {'startMs': '24280', 'endMs': '28270', 'text': None, 'startTime': '0:24'}, {'startMs': '28270', 'endMs': '32770', 'text': None, 'startTime': '0:28'}, {'startMs': '32770', 'endMs': '36690', 'text': None, 'startTime': '0:32'}, {'startMs': '36690', 'endMs': '39860', 'text': None, 'startTime': '0:36'}, {'startMs': '39860', 'endMs': '41510', 'text': None, 'startTime': '0:39'}, {'startMs': '41510', 'endMs': '43949', 'text': None, 'startTime': '0:41'}, {'startMs': '43950', 'endMs': '45800', 'text': None, 'startTime': '0:43'}, {'startMs': '45800', 'endMs': '46969', 'text': None, 'startTime': '0:45'}, {'startMs': '46970', 'endMs': '49170', 'text': None, 'startTime': '0:46'}, {'startMs': '56185', 'endMs': '58100', 'text': None, 'startTime': '0:56'}, {'startMs': '58100', 'endMs': '61239', 'text': None, 'startTime': '0:58'}, {'startMs': '61240', 'endMs': '64809', 'text': None, 'startTime': '1:01'}, {'startMs': '64809', 'endMs': '67310', 'text': None, 'startTime': '1:04'}, {'startMs': '67310', 'endMs': '70820', 'text': None, 'startTime': '1:07'}, {'startMs': '70820', 'endMs': '74850', 'text': None, 'startTime': '1:10'}, {'startMs': '74850', 'endMs': '76000', 'text': None, 'startTime': '1:14'}, {'startMs': '76000', 'endMs': '78780', 'text': None, 'startTime': '1:16'}, {'startMs': '78780', 'endMs': '81030', 'text': None, 'startTime': '1:18'}, {'startMs': '81030', 'endMs': '81863', 'text': None, 'startTime': '1:21'}, {'startMs': '81863', 'endMs': '83840', 'text': None, 'startTime': '1:21'}, {'startMs': '83840', 'endMs': '86490', 'text': None, 'startTime': '1:23'}, {'startMs': '86490', 'endMs': '89250', 'text': None, 'startTime': '1:26'}, {'startMs': '89250', 'endMs': '92157', 'text': None, 'startTime': '1:29'}, {'startMs': '92157', 'endMs': '93880', 'text': None, 'startTime': '1:32'}, {'startMs': '93880', 'endMs': '96759', 'text': None, 'startTime': '1:33'}, {'startMs': '96760', 'endMs': '100500', 'text': None, 'startTime': '1:36'}, {'startMs': '100500', 'endMs': '105500', 'text': None, 'startTime': '1:40'}, {'startMs': '105650', 'endMs': '108480', 'text': None, 'startTime': '1:45'}, {'startMs': '108480', 'endMs': '111570', 'text': None, 'startTime': '1:48'}, {'startMs': '111570', 'endMs': '113180', 'text': None, 'startTime': '1:51'}, {'startMs': '113180', 'endMs': '117300', 'text': None, 'startTime': '1:53'}, {'startMs': '117300', 'endMs': '120250', 'text': None, 'startTime': '1:57'}, {'startMs': '120250', 'endMs': '122390', 'text': None, 'startTime': '2:00'}, {'startMs': '122390', 'endMs': '123820', 'text': None, 'startTime': '2:02'}, {'startMs': '123820', 'endMs': '128820', 'text': None, 'startTime': '2:03'}, {'startMs': '129610', 'endMs': '132040', 'text': None, 'startTime': '2:09'}, {'startMs': '132040', 'endMs': '133122', 'text': None, 'startTime': '2:12'}, {'startMs': '134890', 'endMs': '137380', 'text': None, 'startTime': '2:14'}, {'startMs': '137380', 'endMs': '140130', 'text': None, 'startTime': '2:17'}, {'startMs': '140130', 'endMs': '143450', 'text': None, 'startTime': '2:20'}, {'startMs': '143450', 'endMs': '146920', 'text': None, 'startTime': '2:23'}, {'startMs': '146920', 'endMs': '149680', 'text': None, 'startTime': '2:26'}, {'startMs': '149680', 'endMs': '153750', 'text': None, 'startTime': '2:29'}, {'startMs': '153750', 'endMs': '157290', 'text': None, 'startTime': '2:33'}, {'startMs': '157290', 'endMs': '158870', 'text': None, 'startTime': '2:37'}, {'startMs': '158870', 'endMs': '161540', 'text': None, 'startTime': '2:38'}, {'startMs': '161540', 'endMs': '165409', 'text': None, 'startTime': '2:41'}, {'startMs': '165410', 'endMs': '168270', 'text': None, 'startTime': '2:45'}, {'startMs': '168270', 'endMs': '170350', 'text': None, 'startTime': '2:48'}, {'startMs': '170350', 'endMs': '172910', 'text': None, 'startTime': '2:50'}, {'startMs': '172910', 'endMs': '175170', 'text': None, 'startTime': '2:52'}, {'startMs': '175170', 'endMs': '176380', 'text': None, 'startTime': '2:55'}, {'startMs': '176380', 'endMs': '180560', 'text': None, 'startTime': '2:56'}, {'startMs': '180560', 'endMs': '182760', 'text': None, 'startTime': '3:00'}, {'startMs': '182760', 'endMs': '184370', 'text': None, 'startTime': '3:02'}, {'startMs': '184370', 'endMs': '187209', 'text': None, 'startTime': '3:04'}, {'startMs': '187210', 'endMs': '190080', 'text': None, 'startTime': '3:07'}, {'startMs': '190080', 'endMs': '191300', 'text': None, 'startTime': '3:10'}, {'startMs': '191300', 'endMs': '193370', 'text': None, 'startTime': '3:11'}, {'startMs': '193370', 'endMs': '194996', 'text': None, 'startTime': '3:13'}, {'startMs': '194996', 'endMs': '196830', 'text': None, 'startTime': '3:14'}, {'startMs': '196830', 'endMs': '199940', 'text': None, 'startTime': '3:16'}, {'startMs': '199940', 'endMs': '203000', 'text': None, 'startTime': '3:19'}, {'startMs': '203000', 'endMs': '205640', 'text': None, 'startTime': '3:23'}, {'startMs': '205640', 'endMs': '208810', 'text': None, 'startTime': '3:25'}, {'startMs': '208810', 'endMs': ```

I'm using python 3.9.5 and youtube-search-python  version 1.6.5 on Windows 11 machine.

**Comment by mytja** [comment]
I know I said, I'll fix it soon. I just can't seem to find the time. Sorry for the delay.
