### ISSUE TITLE
error when getting videos from channel id

### ISSUE THREAD

**Issue by chirag127** [alexmercerind/youtube-search-python#183]
getting error keyerror sidebar, but there is no error in videoids from playlistid.

**Comment by mytja** [comment]
I cannot help you if you don't give me Playlist ID and a minimal reproducible sample

**Comment by chirag127** [comment]
Na, it was my mistake in the code. When i was trying to make minimum reproduceable code i found my mistake.


By the way, if i want to make a search filter of "closedcaption", how do i pass it ?
