### ISSUE TITLE
Questions rather than issue: how to add some values to the result?

### ISSUE THREAD

**Issue by BernardG** [alexmercerind/youtube-search-python#188]
I have no idea how difficult it would be, as I am more a Python beginner than an expert, even if I am not a beginner in programming.
What would be the process to add the full description, rather than just the description snippet, as well as the author of the vidéo?
If it is not too complex, I would attempt to tackle this, but would need some guidance about where the modifications would need to be made.

AS of now, I do lookups with the "other" library (pytube), but it makes it awfully slow.

**Comment by mytja** [comment]
If you mean getting the full description on *Search classes, it's not possible. If YouTube doesn't display that on their search page, it cannot be added to this library. You can however do a Video.getInfo() for each video in the search result, but that would be painfully slow, as you have already mentioned.

The author of the video is already in the response in *Search classes. Have a look at [example response](https://github.com/alexmercerind/youtube-search-python#search-for-only-videos).

Besides that, this library is getting retired very very soon #189

**Comment by BernardG** [comment]
Thanks for your answer, and for letting me know the library is getting retired
