### ISSUE TITLE
Python 2 support issue

### ISSUE THREAD

**Issue by mytja** [alexmercerind/youtube-search-python#19]
Hello!
Tried to import your library with
`pip install youtube-search-python`
but, when I import it from Python 2, I get this error, which I don't get, if I manually add this library into my project folder:
```
Traceback (most recent call last):
  File "F:\MyAssistantOS\recognition\my.py", line 15, in <module>
    from youtubesearchpython import searchYoutube
  File "C:\Python27\lib\site-packages\youtubesearchpython\__init__.py", line 1, in <module>
    from youtubesearchpython.videos__search import SearchVideos
  File "C:\Python27\lib\site-packages\youtubesearchpython\videos__search.py", line 3, in <module>
    from youtubesearchpython.__requesthandler import requesthandler
  File "C:\Python27\lib\site-packages\youtubesearchpython\__requesthandler.py", line 2, in <module>
    from urllib.request import urlopen
ImportError: No module named request
```
Can you fix this?
Thank you

**Comment by alexmercerind** [comment]
Hi!
Which exact Python 2 version are you using?
This seems really confusing.

**Comment by mytja** [comment]
I'm using Python 2.7.

**Comment by alexmercerind** [comment]
@mytja 
I feel that you might be using older version of module from pip.

Try running the command:

```
pip install --upgrade youtube-search-python
```

**Comment by alexmercerind** [comment]
Hi @mytja!
I closed this issue. Feel free to discuss and leave feedback. 
I'm not able to reproduce this issue. My above comment should fix the problem for you.
Thanks a lot for your support!

**Comment by alexmercerind** [comment]
I have literally no idea what's going wrong with it.

Let me know if you find any possible fix.

**Comment by mytja** [comment]
Found the error. Will create a pull request within 12 hours.
😀

**Comment by mytja** [comment]
... or maybe in 1 hour

**Comment by mytja** [comment]
#20 is prepeared.

**Comment by mytja** [comment]
Build test: https://travis-ci.org/github/mytja/youtube-search-python/builds/721918749
