### ISSUE TITLE
Add subtitle in result

### ISSUE THREAD

**Issue by gaetan1903** [alexmercerind/youtube-search-python#2]
It is possible to get the subtitle of the video ?

**Comment by alexmercerind** [comment]
I appreciate your idea, but I have already added "nearly everything" that YouTube offers in its search result page.

Adding more features will require, more network requests (per video) and will cause heavy performance expenses too.

Apart from that, YouTube subtitles are shown with YouTube's own fancy JavaScript (not present in the HTML document), so we cannot deal with it. Most features that a generic search result contains, are already implemented.
I'll keep adding fixes for the already added features in future, as YouTube messes a lot with websites.

Leaving the issue opened.
Thankyou for feedback. 😃
