### ISSUE TITLE
Add channel id in the results

### ISSUE THREAD

**Issue by saturnus-ringar** [alexmercerind/youtube-search-python#24]
It would be great if the channel id was included in the search results. I don't know how this works on youtube, but an example is this:

https://www.youtube.com/watch?v=EDwb9jOVRtU

From the source:
`<a class="yt-simple-endpoint style-scope yt-formatted-string" spellcheck="false" href="/channel/UC81VD6eeuLLSfyY_D-N8sVw" dir="auto">Madonna</a>`

**Channel**: UC81VD6eeuLLSfyY_D-N8sVw

**Comment by alexmercerind** [comment]
👌 Checkout the master...

Let me know if it is fine, because I can't tell if all regions of world get same response from YouTube.
It is working for me, I'm getting channel IDs in the result now.

❎ Closing this one.

**Comment by alexmercerind** [comment]
```bash
pip3 install youtube-search-python==1.3.1
```
