### ISSUE TITLE
Access title and links from search_result

### ISSUE THREAD

**Issue by JAXPARROW** [alexmercerind/youtube-search-python#27]
from the search_result is there a way i can access only individuals items, let's say title and link so i can process them further into my custom function?

**Comment by alexmercerind** [comment]
Hi,
I assume this is just a question regarding the usage. You can just acquire the search result dictionary & use the data the way you want.

**For example, in the following script I'm printing video title & link of first video in the result.**

```py
from youtubesearchpython import SearchVideos
import json

index = 0

search = SearchVideos("NoCopyrightSounds").result()
result = json.loads(search)

#  You can alternatively simply write...
#  result = SearchVideos("NoCopyrightSounds", mode = "dict").result()


if search != None:
    print("The first video is:")
    print("Video Title: " + result["search_result"][index]["title"])
    print("Video URL  : " + result["search_result"][index]["link"])
else:
    print("Check your internet connection...")
```
