### ISSUE TITLE
Usage of "offset" parameter

### ISSUE THREAD

**Issue by FelixFox** [alexmercerind/youtube-search-python#28]
Hello, @alexmercerind ! Nice work!

I have a question about the "offset" param, which is used for the initialization of SearchVideos and SearchPlaylists objects. I have not found its usage in any of the submodules of the package "youtubesearchpython". 

Is this param used somewhere?

**Comment by alexmercerind** [comment]
Hi @FelixFox!
The ```offset``` parameter can be used to switch between the result pages from YouTube. It's default value is 1 (i.e. gives search results on the first page).
You can set to to 2 for getting results of the next page etc.

**Following URL query is formed for your reference**
https://github.com/alexmercerind/youtube-search-python/blob/2d6284b3cf2df329f28348bbdd481014ba263c4a/youtubesearchpython/__requesthandler.py#L13-L17

Thanks. 
Feel free to ask or leave feedback.
