### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by tobip** [alexmercerind/youtube-search-python#31]
Question: Do you think it might be useful to set a default language for the search url?
At the moment I am traveling abroad and the information like uploaded x months ago is in cyrillic letters what unfortunately I am barely able to read.

So in my specific case it would be useful if the script would use english as a default language.
At the same time I can see that probably others like the fact that the script is using their local language.

To be honest I am not clear what could be a easy and nice solution in this case...

**Comment by alexmercerind** [comment]
It is most likely possible. I cannot guarantee if I'll be able to add any such feature yet.

Possibly there is a query parameter in YouTube website already, which we can give to YouTube to get results according to that specified region. Region & language based problems aren't any new for this project.

Greetings 🍀

**Comment by alexmercerind** [comment]
:tada: alexmercerind@a30df45ac0b2197cd3e4c6a3e3cd03a5a4a1676d

Now you can get search results in different languages & from different region as follows:

```py
from youtubesearchpython import SearchVideos, SearchPlaylists

videos = SearchVideos(
    "NoCopyrightSounds",
    offset = 1,
    mode = "json",
    max_results = 20,
    language = "en-US",           # Sets language
    region="US"                   # Sets region to get videos accordingly
)
videosResult = videos.result()
print(videosResult)
```

**Comment by alexmercerind** [comment]
@tobip 

Please let me know if something breaks or doesn't work.

**Comment by tobip** [comment]
Awesome!
Seems to work for me. :+1:
