### ISSUE TITLE
None Results

### ISSUE THREAD

**Issue by Rewzaw** [alexmercerind/youtube-search-python#33]
test.py

    from youtubesearchpython import SearchVideos

    search = SearchVideos("NoCopyrightSounds", offset=1, mode="json", max_results=20)

    print(search.result())

terminal

    python .\test.py
    None

**Comment by alexmercerind** [comment]
Are you using latest version 1.3.2 from the PyPI?

**Comment by alexmercerind** [comment]
I'm unable to reproduce this issue on the latest v1.3.2 version of youtube-search-python.
Feel free to reopen incase you feel something is wrong.

Thankyou 🍀
