### ISSUE TITLE
Return None 

### ISSUE THREAD

**Issue by MariaJsn** [alexmercerind/youtube-search-python#34]
Hi,

When I tried to run example project I am getting the None error. 
Please can you check it?

Thanks

**Comment by alexmercerind** [comment]
Are you using latest v1.3.2 from PyPI?

**Comment by mytja** [comment]
Same as #33

**Comment by MariaJsn** [comment]
yes I am using the latest version

**Comment by mytja** [comment]
@alexmercerind touched this issue here: #36 , so did you encouter an Network issue? And which Python version are you using?

**Comment by MariaJsn** [comment]
I am using the Python 3.9.0 version and tried with your code. Also I am using Mac.

**Comment by mytja** [comment]
Hmmm. It seems like Python changed a lot in 3.9! Quite a lot of things now don't work in Python 3.9! Maybe try downgrading to 3.7 or 3.8 until we find source of the issue!
Sorry for your inconvenience

**Comment by MariaJsn** [comment]
I install 3.7 version and tried with terminal and get the same error.
I am using this command in terminal, is it wrong? python3.7 Usage\ Example.py
and result is ;
None 
None

**Comment by alexmercerind** [comment]
Hi @MariaJsn!

Thanks a lot for helping out and spending your time to get this bug fixed.
May I get the log.txt generated by running the following script:

```py
from youtubesearchpython import SearchVideos

if __name__ == '__main__':
    
    videos = SearchVideos('NoCopyrightSounds')
    
    with open('log.txt', 'a', encoding = 'utf_8') as file:
        if (videos.result() == None):
            print('alexmercerind/youtubesearchpython failed.')
            fields = vars(videos)
            for key in fields:
                file.write(f'\n==========self.{key}\n==========')
                file.write(str(fields[key]))
            print('Debugging log saved in log.txt.')
        else:
            print('alexmercerind/youtubesearchpython worked properly.')
```

And thanks a lot @mytja for taking a look at the issue. I believe this bug is not because of 3.9 as I'm unable to reproduce it.

**Comment by MariaJsn** [comment]
This is the log file:

==========self.offset
==========1
==========self.mode
==========json
==========self.keyword
==========NoCopyrightSounds
==========self.max_results
==========20
==========self.searchPreferences
==========EgIQAQ%3D%3D
==========self.language
==========en-US
==========self.region
==========US
==========self.networkError
==========True

**Comment by alexmercerind** [comment]
I don't know what is going wrong...
My log.txt looks as [this](https://github.com/alexmercerind/youtube-search-python/files/5622367/log.txt).

**Comment by MariaJsn** [comment]
I think there is a problem in Mac. When I tried with windows pc it worked but Mac not.

**Comment by alexmercerind** [comment]
I'm unable to reproduce. PRs are always welcomed.
