### ISSUE TITLE
Location and Region Ignored

### ISSUE THREAD

**Issue by x011** [alexmercerind/youtube-search-python#37]
`search = SearchVideos("Test", offset = 1, mode = "json", max_results = 20, language="en-US", region="US")`

Example video title on search results:
`
"title": "\u041a\u0430\u043a \u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c \u0422\u0412 IPTV \u0411\u0415\u0421\u041f\u041b\u0410\u0422\u041d\u041e : \u0422\u0412 \u043a\u0430\u043d\u0430\u043b\u044b \u043d\u0430 \u0410\u043d\u0434\u0440\u043e\u0438\u0434",`

I'm getting results based on my location not on language and region arguments, which are being ignored.
Is there a way to force results in the specified language and region without having to rely on a vpn/proxy?
Thank you.

**Comment by alexmercerind** [comment]
Hi there!
There is nothing about it I think I can do I believe.

The optional parameter sets the persist_gl as "1" and gl as "en-US" in the query.
You can confirm it by setting following setting in the YouTube while searching & you'll notice these parameters automatically get added to the URL.
![wqeqwe](https://user-images.githubusercontent.com/28951144/100832344-ab114180-348d-11eb-8554-4a89d28bf503.PNG)

Thus, resulting URL looks like:
https://www.youtube.com/results?search_query=NoCopyrightSounds&sp=EgIQAQ%253D%253D&page=1&persist_gl=1&gl=US

The language parameter on the other hand changes language of response from YouTube by sending custom header in the request.

**Comment by alexmercerind** [comment]
I'll try to find, if there is some other way of getting results according to any specific location.
Thankyou. Closing for now.
