### ISSUE TITLE
YouTube removed the page parameter

### ISSUE THREAD

**Issue by ton1ght** [alexmercerind/youtube-search-python#39]
Hello,

i have noticed that the page parameter isn't working as intended. Minimal example to reproduce:

```python
from youtubesearchpython import CustomSearch

first = CustomSearch('test', searchPreferences="CAM%253D", page=1)
second = CustomSearch('test', searchPreferences="CAM%253D", page=2)

print(first.result() == second.result()) # returns true
```

The searchPreferences are set to order the results by their respective view count.

I have manually tested the page parameter and it seems like that YouTube has disabled this functionality in order to make you use the official API. I really do not want to use their API as this requires an account. Are you aware of a method to obtain more than 20 search results without using their API?

The only method I found involves Selenium which basically just scrolls down the page to load more results.

**Comment by alexmercerind** [comment]
Hi there @ton1ght!
Yeah, I'm already aware myself that page optional parameter has stopped working few days back.
I actually found a way to get more than 20 results, but I'm still collecting more information about it.

**Comment by alexmercerind** [comment]
Hi there @ton1ght!

Now you may get the results on next pages as [here](https://github.com/alexmercerind/youtube-search-python#mag_right-getting-result-on-the-next-pages).

Thankyou 🍀!
Closing this issue.
