### ISSUE TITLE
Set a maximum number of results

### ISSUE THREAD

**Issue by marsarem** [alexmercerind/youtube-search-python#4]
It would be nice if we could specify the maximum number of results that we want.

**Comment by alexmercerind** [comment]
In progress...

**Comment by marsarem** [comment]
I created a fork. You can have a look

**Comment by alexmercerind** [comment]
Hello there! 

Check my latest commit. Added to master!

**I appreciate your contribution but your implementation has problems:**
1. It does not give performance benefits to user, if he chooses less number of results.
2. If the user enters the "maximum" greater than the number of results YouTube provided, then error will be raised.

Thankyou!

**Comment by marsarem** [comment]
`max_results` doesn't specify the number of results we will have because the results start with the id 0 and end with the id equal to `max_result`. So we will have `max_result+1` results

**Comment by alexmercerind** [comment]
If you set max_results  = 10, you will get 10 results.

I get, what you are saying but I have reduced the range in results. (Incase something wrong happens with request or something.)
