### ISSUE TITLE
The latest version on pypi seems to miss some files

### ISSUE THREAD

**Issue by kaisuto** [alexmercerind/youtube-search-python#40]
![image](https://user-images.githubusercontent.com/5660769/103016722-79b3ff00-457d-11eb-834f-f81d2fb92ea5.png)
![image](https://user-images.githubusercontent.com/5660769/103016787-93554680-457d-11eb-906c-11cb47f512c7.png)
It only packages legacy directory, no internal and handlers.

**Comment by alexmercerind** [comment]
Hi @kaisuto !

Really sorry for the inconvenience, I released a newer version 1.3.4 on PyPI now, enjoy the new features.

Thanks for love.

**Comment by kaisuto** [comment]
Thank you for the quick fix! : )
