### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by Ns-AnoNymouS** [alexmercerind/youtube-search-python#41]
Hello sir try to add search via id. So that we can get the data from YouTube link too. Thank you sir

**Comment by alexmercerind** [comment]
Hi there @Ns-AnoNymouS!

I have added three new methods:
Video.get
Video.getInfo
Video.getFormats

Now you can get all the video information using a video ID or URL.
See example here: [link](https://github.com/alexmercerind/youtube-search-python#getting-video-information-using-video-link-or-video-id)

Thankyou! 🍀

Let me know if something breaks or works.
Closing issue.
