### ISSUE TITLE
Could not parse YouTube response

### ISSUE THREAD

**Issue by rmills** [alexmercerind/youtube-search-python#49]
Something broke between 1.3.3 and 1.3.6, at least in CustomSearch(), nearly every results returns 0 results or throws a "Could not parse YouTube response." in 1.3.6. What makes no sense is why some keywords work, but most fail. Forgive the language but I was pulling my hair out and just started throwing words at it, with a bit of trial and error I found two words that either always worked or always failed. On 1.3.6 searching with CustomSearch() with the search param "CAASBAgBEAE", "music" currently returns 48 results but "fuck" returns 0 results, on 1.3.3 with the exact same code "fuck" returns 48 results.

 The code is a bit to granular for me to trace it back quickly. but I would guess something from commit 4c731bbd86d8cef2ea1431c2843b2d88ffc176db is to blame as _youtubesearchpython/handlers/requesthandler.py -> __parseSource()_ is throwing the exception.

**Comment by alexmercerind** [comment]
Thankyou for letting me know. Let me see what I can do about this.

**Comment by alexmercerind** [comment]
```py
print(CustomSearch("fuck", "CAASBAgBEAE").result())
```

According to you this script should return zero results or throw an exception.
But, it works fine for me & I'm unable to reproduce it.
May you please provide a sample reproducing code for me to regenerate the issue.

**Comment by rmills** [comment]
Just ran my test script again and it worked so I need to run a bunch more keywords again, I will update when I find something consistent again.

**Comment by alexmercerind** [comment]
Feel free to reopen as you reproduce.

**Comment by rajorpratyush** [comment]
seeing the same issue, again and again, it's not reproducible for any specific use case, just happens randomly and mostly happens when you call next page results(pagination).

**Comment by alexmercerind** [comment]
@rajorpratyush, it's impossible to fix anything without reproduction of issue.
Or even give code that fails randomly.

I can only help if one provides the faulty code not just comments.

**Comment by rmills** [comment]
The issue happened between 1.3.3 and 1.3.6, I still use 1.3.3 without issue.

**Comment by momonala** [comment]
Just a hint for this - I got the same issue when passing in a non-string into the `VideoSearch` constructor: 

```python
In [3]: videosSearch = VideosSearch({"id": "Send Me on My Way Rusted Root"}, limit=1)
'NoneType' object is not subscriptable
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/.local/lib/python3.9/site-packages/youtubesearchpython/handlers/requesthandler.py:54, in RequestHandler._parseSource(self)
     53         self.responseSource = self._getValue(json.loads(self.response), fallbackContentPath)
---> 54         self.continuationKey = self._getValue(self.responseSource[-1], continuationKeyPath)
     55 except Exception as e:

TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
Input In [3], in <module>
----> 1 videosSearch = VideosSearch({"id": "Send Me on My Way Rusted Root"}, limit=1)

File ~/.local/lib/python3.9/site-packages/youtubesearchpython/search.py:148, in VideosSearch.__init__(self, query, limit, language, region, timeout)
    146 self.searchMode = (True, False, False)
    147 super().__init__(query, limit, language, region, SearchMode.videos, timeout)
--> 148 self.sync_create()
    149 self._getComponents(*self.searchMode)

File ~/.local/lib/python3.9/site-packages/youtubesearchpython/core/search.py:30, in SearchCore.sync_create(self)
     28 def sync_create(self):
     29     self._makeRequest()
---> 30     self._parseSource()

File ~/.local/lib/python3.9/site-packages/youtubesearchpython/handlers/requesthandler.py:57, in RequestHandler._parseSource(self)
     55 except Exception as e:
     56     print(e)
---> 57     raise Exception('ERROR: Could not parse YouTube response.')

Exception: ERROR: Could not parse YouTube response.
```

vs this worked fine: 

```python
In [4]: videosSearch = VideosSearch("Send Me on My Way Rusted Root", limit=1)

In [5]:
```
