### ISSUE TITLE
Not decode utf-8 

### ISSUE THREAD

**Issue by gaetan1903** [alexmercerind/youtube-search-python#5]
the result not showhing proprely "é " or something like that , 
é è ù and other...

**Comment by alexmercerind** [comment]
Under progress...

**Comment by alexmercerind** [comment]
JSON does not store the strings in that encoding. You need to yourself decode the strings at the time of rendering.

Following example gives information:
```
>>> string = "\u041d\u0430\u0441\u0442\u044f \u0438 \u0441\u0431\u043e\u0440\u043d\u0438\u043a \u0432\u0435\u0441\u0451\u043b\u044b\u0445 \u0438\u0441\u0442\u043e\u0440\u0438\u0439"
>>> bytes(string, encoding="unicode_escape").decode("unicode_escape")
'Настя и сборник весёлых историй'
```

**Comment by alexmercerind** [comment]
Closing issue for now!

**Comment by alexmercerind** [comment]
Another example:
```
>>> string = "Crime Patrol - \u0915\u094d\u0930\u093e\u0907\u092e \u092a\u0947\u091f\u094d\u0930\u094b\u0932 \u0938\u0924\u0930\u094d\u0915 - Episode 495 - 17th April 2015"
>>> bytes(string, encoding="unicode_escape").decode("unicode_escape")
'Crime Patrol - क्राइम पेट्रोल सतर्क - Episode 495 - 17th April 2015'
>>> 
```

**Comment by gaetan1903** [comment]
in case of "list" result, it doesn't work

**Comment by gaetan1903** [comment]
```
str_= "ma\xc9"
bytes(str_, encoding="unicode_escape").decode("unicode_escape")
```
result may be maé , but don't work

**Comment by alexmercerind** [comment]
I will commit some minor changes tomorrow. I don't have my PC presently. (Using GitHub mobile).

Thankyou for information.

**Comment by Vitaman02** [comment]
Converting to bytes and decoding them to unicode_escape did not work for me. I tried appending 20 song names in a list and they are all in unicode, because they are in a different language. I tried adding it to the library but that didn't work either. I tried converting them to strings with encoding "unicode_escape". I did this with utf8 and that didn't work either.

**Comment by alexmercerind** [comment]
@gaetan1903 and @Vitaman02 .  Check the new commit. Try using "dict" or "list" as mode.
And let me know.

Now all unicode characters and emojis are perfectly showed.
Sorry for delay.

**Comment by Vitaman02** [comment]
This didn't work although the bytes converted to "\u00ce" from "\xaeb". So it changed from utf8 to unicode and I didn't see the change. I tried chaning "requesthandler.py" to use the "requests" library but that didn't work either.

**Comment by Vitaman02** [comment]
Thanks. The `mode="dict"` works and `mode="list"` works, but json does not work and the characters are in unicode, although they were encoded to utf8.

**Comment by alexmercerind** [comment]
@Vitaman02 I'm aware of that, but there is nothing I can do.

The converting to bytes method will now work fine for mode = "json".
JSON does not support that encoding. You have to yourself encode (convert to bytes), and then decode in "unicode_escape", at the time of rendering .

Thankyou!

**Comment by Vitaman02** [comment]
It's all good, `dict` and `json` are almost the same thing so it's ok. No worries.
