### ISSUE TITLE
StreamURLFetcher not working

### ISSUE THREAD

**Issue by radiolondra** [alexmercerind/youtube-search-python#54]
**OS**: Windows 10
**kivy**: 2.0 stable
**youtube-search-python**: 1.4.1
**pyTube**: 10.5.1

I'm trying to get Youtube stream urls using `StreamURLFetcher`.

```
    def stream_test(self):
        link = 'https://www.youtube.com/watch?v=YQHsXMglC9A'
        fetcher = StreamURLFetcher()
        stream = Video.get(link)
        url = fetcher.getAll(stream)
        print('URLS:', url)
```

This is the result:

```
URLS: <coroutine object StreamURLFetcher.getAll at 0x0E1C4930>
 <string>:112: RuntimeWarning: coroutine 'StreamURLFetcher.getAll' was never awaited
 RuntimeWarning: Enable tracemalloc to get the object allocation traceback
 <string>:112: RuntimeWarning: coroutine 'Video.get' was never awaited
 RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

The same happens using the example in the README (using `get `instead of `getAll`)

    def stream_test(self):
        fetcher = StreamURLFetcher()
        video = Video.get("https://www.youtube.com/watch?v=aqz-KE-bpKQ")
        url = fetcher.get(video, 251)
        print(url)

the result is the same:

```
<coroutine object StreamURLFetcher.get at 0x0E7B38E8>
 <string>:112: RuntimeWarning: coroutine 'StreamURLFetcher.get' was never awaited
 RuntimeWarning: Enable tracemalloc to get the object allocation traceback
 <string>:112: RuntimeWarning: coroutine 'Video.get' was never awaited
 RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

Any idea?
Thanks

**Comment by alexmercerind** [comment]
Hi there @radiolondra !

Are you importing the library from `__future__` subpackage?

If yes, then you need to call await.

**Comment by alexmercerind** [comment]
Is your issue resolved?

**Comment by radiolondra** [comment]
Oh my... YES!! you'r right! I'm using the async version so I've to async/await:

```
async def stream_test(self):
    fetcher = StreamURLFetcher()
    await fetcher.getJavaScript()
    video = await Video.get("https://www.youtube.com/watch?v=aqz-KE-bpKQ")
    url = await fetcher.get(video, 251)
    print(url)
```

and now it works perfectly! Thanks and sorry for my stupid mistake.
