### ISSUE TITLE
Duration filter

### ISSUE THREAD

**Issue by helloworldkr** [alexmercerind/youtube-search-python#58]
Is there any way to get results with duration filter.

Youtube on its page has a duration filter with short (<4mins) and a long(>20mins) things.

![image](https://user-images.githubusercontent.com/9402190/111061246-66536880-84c8-11eb-84c7-a7f7fcf66bbf.png)

It will be really helpful if you can add this in case this is not available.

**Comment by alexmercerind** [comment]
Hi,

As you can see that there is a "sp" parameter in the search query ("EgIYAQ%253D%253D"). Unescape that string & pass as the second parameter while instantiating the object of `CustomSearch` class. 

You'll get your required result with filter.

I've mentioned this in the documentation.

![sdada](https://user-images.githubusercontent.com/28951144/111061338-d6fa8500-84c8-11eb-8f73-e371b4a0f2f5.PNG)

Thanks.

**Comment by alexmercerind** [comment]
@helloworldkr .
Unescaped string is "EgIYAQ%3D%3D" incase you want more info.

**Comment by helloworldkr** [comment]
Thanks @alexmercerind
