### ISSUE TITLE
How can i go directly to a specific search page?

### ISSUE THREAD

**Issue by kirill505** [alexmercerind/youtube-search-python#59]
Please tell me how you can go directly to a specific search page? For example, if I have already downloaded 200 videos, how can I immediately start downloading with 201 videos for a specific search term?

**Comment by alexmercerind** [comment]
Every search page has a `continuationKey` which is used to get result of next page.
This project simulates the requests from a web browser. And a web browser can't do that, thus this project can't do that.

**Comment by alexmercerind** [comment]
I have already given a very handy `next` attribute to simulate going to next search page.
