### ISSUE TITLE
Bad title

### ISSUE THREAD

**Issue by marsarem** [alexmercerind/youtube-search-python#6]
There are the date of the video, the channel name and the number of views in the title of each video.

```
{
    "search_result": [
        {
            "index": 0,
            "id": "RQ5IkSeMQbc",
            "link": "https://www.youtube.com/watch?v=RQ5IkSeMQbc",
            "title": "Teyeq - Demons [NCS Release] de NoCopyrightSounds il y a 22 heures 2 minutes et 35 secondes 238 806 vues\"",
            "channel": "",
            "duration": "",
            "views": 806,
            "thumbnails": [
                "https://img.youtube.com/vi/RQ5IkSeMQbc/default.jpg",
                "https://img.youtube.com/vi/RQ5IkSeMQbc/hqdefault.jpg",
                "https://img.youtube.com/vi/RQ5IkSeMQbc/mqdefault.jpg",
                "https://img.youtube.com/vi/RQ5IkSeMQbc/sddefault.jpg",
                "https://img.youtube.com/vi/RQ5IkSeMQbc/maxresdefault.jpg"
            ]
        },...
```
The title is : Teyeq - Demons [NCS Release] de NoCopyrightSounds il y a 22 heures 2 minutes et 35 secondes 238 806 vues\
(`Teyeq - Demons [NCS Release] de NoCopyrightSounds il y a 22 heures 2 minutes et 35 secondes 238 806 vues` means `Teyeq - Demons [NCS Release] from NoCopyrightSounds 22 hours, 2 minutes and 35 seconds ago 238806 vues` in french.)
I don't understand why there are the date of the video, the channel name and the number of views in the title of each video.

Also there is nothing in the field `channel`

I checked in youtude source code and the `title` is correct but the `label` isn't.
```
{"url":"https://i.ytimg.com/vi/rLe5S1UKPko/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==\u0026rs=AOn4CLDCBddTGwin1yccKbIbyasMJC4qkg","width":336,"height":188}]},
"title":{"runs":[{"text":"Meryl - Coucou"}],"accessibility":{"accessibilityData":{"label":"**Meryl - Coucou de Meryl270 il y a 4 mois 2 minutes et 39 secondes 4 019 653 vues**"}}}
```

**Comment by alexmercerind** [comment]
This seems a region issue.

**Comment by alexmercerind** [comment]
I target next release with the fix for this issue.

Thankyou for information.
I'll try to fix this by tomorrow.

**Comment by alexmercerind** [comment]
@marsarem I fixed this issue. Updating the repo... Feel free to open if this occurs next time.
The script should work fine in all regions now.

Thankyou for your support.

**Comment by alexmercerind** [comment]
alexmercerind@37c3011.

If the issue still exists, feel free to reopen.

**Comment by alexmercerind** [comment]
I also added live videos/streams in the search results now. It is now pretty much safe to use.
