### ISSUE TITLE
Quota Limit Reached?

### ISSUE THREAD

**Issue by BertAssistant** [alexmercerind/youtube-search-python#60]
Hi, I'm new at Github and Python. I'm using this module to stream music and deploy it on my LINE Bot. So, I found out that when I input the keyword quickly, the bot would show me "Could not make request". However, when I try it on my IDLE console, the code would run well eventhough I input it quickly. Is there a bug or is it just the error in my code? Any help will be appriciated.

Screenshot the log from my server (replit.com)
![635150](https://user-images.githubusercontent.com/80688789/111153346-69cc1a00-85c4-11eb-96ed-2b02a29eb323.jpg)

Screenshot error log from my bot
![image](https://user-images.githubusercontent.com/80688789/111153497-a0a23000-85c4-11eb-9b1a-ec482e5cf914.png)
![image](https://user-images.githubusercontent.com/80688789/111153692-d810dc80-85c4-11eb-8bd3-9d2cc42f0dc2.png)
![image](https://user-images.githubusercontent.com/80688789/111153762-e9f27f80-85c4-11eb-9121-7e41567d6a41.png)

My code:
![image](https://user-images.githubusercontent.com/80688789/111154036-49508f80-85c5-11eb-8003-1c614235c192.png)

My IDLE:
![image](https://user-images.githubusercontent.com/80688789/111154290-a77d7280-85c5-11eb-918b-638474a68639.png)

**Comment by alexmercerind** [comment]
Hi @BertAssistant !

I'm kinda confused about this one.

**Comment by alexmercerind** [comment]
Hi @BertAssistant !

Can you please remove the following line from your code & let me know if it still shows that on terminal?
```py
url = StreamURLFetcher().get(target, 251)
```

Because that's the only thing that can go wrong, I guess.

**Comment by BertAssistant** [comment]
> Hi @BertAssistant !
> 
> Can you please remove the following line from your code & let me know if it still shows that on terminal?
> 
> ```python
> url = StreamURLFetcher().get(target, 251)
> ```
> 
> Because that's the only thing that can go wrong, I guess.

Here is my code now :
![image](https://user-images.githubusercontent.com/80688789/111158438-9b47e400-85ca-11eb-897a-1c4bc0541fcd.png)

Here is the log :
![image](https://user-images.githubusercontent.com/80688789/111158675-e661f700-85ca-11eb-80b0-31a9040ed654.png)

I think the main problem (Could not make requests) is StreamURLFetcher(). On my local console it works fine, but not with the server console

**Comment by alexmercerind** [comment]
Hello @BertAssistant !

As you probably read my documentation of the project, the  `StreamURLFetcher` is derived from `PyTube` & its a slow process.

Thing is that, when you message too frequently, the things get kinda bad as it uses some global variables, which do not make it thread safe.
So,
all I can say is to change this line: 
```py
url = StreamURLFetcher().get(target, 251)
```
to:
```py
# Store this globally.
fetcher = StreamURLFetcher()

def yourMessageFunction(self, ...):
    # Address the object.
    url = fetcher.get(target, 251)
```

By this, the performance will also improve & possibly your bug will also get fixed.

You can see [this](https://github.com/raitonoberu/realmusicbot/blob/master/realmusicbot/music_provider.py) project from someone else, how he/she has stored the object globally.

**Comment by alexmercerind** [comment]
Hope this gets it resolved.
Thanks.

Closing. Feel free to make further query.
