### ISSUE TITLE
next page result with Customsearch

### ISSUE THREAD

**Issue by helloworldkr** [alexmercerind/youtube-search-python#64]
I need to get next page result with Customsearch as i get with
 await videosSearch.next()

I tried to use next() with customsearch but this doesnt seem to be working

**Comment by alexmercerind** [comment]
May you please provide a code snippet to reproduce the mentioned issue.

**Comment by helloworldkr** [comment]
Hi for the response,
the issue is solved

I was using a wrong import 

I was importing 
from youtubesearchpython import *

but I should have been importing 
from youtubesearchpython.__future__ import *

**Comment by alexmercerind** [comment]
@helloworldkr glad to hear. you mentioned wrong person though 😅 . nevermind.
