### ISSUE TITLE
ERROR: Could not make request

### ISSUE THREAD

**Issue by DanielSh02** [alexmercerind/youtube-search-python#65]
Whenever I call the function VideosSearch, I get the error from line 39 of requesthandler.py "ERROR: Could not make request." This happens even when I just copy and paste the examples from the readme.

**Comment by DanielSh02** [comment]
Whenever I call the function VideosSearch, I get the error from line 39 of requesthandler.py "ERROR: Could not make request." This happens even when I just copy and paste the examples from the readme.

**Comment by alexmercerind** [comment]
Which platform?
Are you able to access YouTube from browser?

**Comment by DanielSh02** [comment]
Using Mac OSX Catalina. I can access YouTube from browser.

**Comment by westoun** [comment]
FYI: I recently encountered "ERROR: Could not make request.", also on Mac OSX.
For me,  restarting my internet connection fixed it.

**Comment by mat-hil** [comment]
Maybe if it is helpful for someone else. What worked for me (Big Sur):
Macintosh HD > Applications > Python3.X  > "Install Certificates.command"

From https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org
