### ISSUE TITLE
Getting error when using Video.getInfo to get information video ID.

### ISSUE THREAD

**Issue by minbayevb** [alexmercerind/youtube-search-python#66]
I'm getting two errors. 1: HTTP Error 429: Too Many Requests. 2: Exception: ERROR: Could not make request. Help please!

**Comment by alexmercerind** [comment]
Hi @minbayevb !

Are you able to access YouTube from your web browser from the same device (IP address)?

**Comment by minbayevb** [comment]
I have access to Youtube

**Comment by minbayevb** [comment]
I fixed, thank you!

**Comment by StarkBotsIndustries** [comment]
> I fixed, thank you!

If it was Windows, can you tell how?
