### ISSUE TITLE
descriptionSnippet returns None

### ISSUE THREAD

**Issue by hatefulyak** [alexmercerind/youtube-search-python#70]
Search results return None for descriptionSnippet fields for any type of search query. Tried the example searches and Harry Styles custom search too.
Is this an issue related to not using YouTube API v3 ?

**Comment by mytja** [comment]
@alexmercerind has fixed it in v1.4.5
Please upgrade `youtube-search-python`.
`pip install youtube-search-python --upgrade`

**Comment by alexmercerind** [comment]
This seems to be still existing for some reason.

**Comment by alexmercerind** [comment]
This should be fixed again. Someone pinged me on Discord & I could confirm that `descriptionSnippet` was `None`, so I made little fix. And, now it turns out YouTube reverted it.

Anyways, its working again now.
