### ISSUE TITLE
Scrapping comments

### ISSUE THREAD

**Issue by hatefulyak** [alexmercerind/youtube-search-python#71]
Is there a future scope of scrapping comments off of a video ?

**Comment by alexmercerind** [comment]
I can figure out everything that one might need, but I'm no longer actively adding features to the project. I'm having my focus shifted to some other projects currently.
Looking forward to it in future.

**Comment by hatefulyak** [comment]
Sure thing. I will also give it a try and send a pull request for your review.
Thank You for this repo 👍

**Comment by lodenrogue** [comment]
@AlexandreOuellet Are you looking for someone to take over the maintenance of this project?

**Comment by alexmercerind** [comment]
@lodenrogue you possibly mentioned the wrong person.
I maintain this project, although I'm not actively adding new features as it's very time consuming process to keep looking after things before YouTube breaks it, though I will keep the existing functionalities functioning. Apart from that, I haven't really received any benefit after spending so much time on this project, so I'm not interested.

I look forward to contributions from community & your contributions are also welcomed.
Thanks.

**Comment by lodenrogue** [comment]
Sorry about that. I assumed the name that came up after the @ was you. No worries though.

**Comment by mytja** [comment]
YouTube made such a strong and encrypted API for comments, which I couldn't find in network tab.
My guess is, that it generates on server side and is video specific...
You also have to generate all kinds of cookies and keys...
Thus I personally am unable to make this happen without direct scraping from page...

**Comment by mytja** [comment]
This is gonna be closed once #154 gets merged.

Sorry it took me so long for it.
