### ISSUE TITLE
searchPreferences not working?

### ISSUE THREAD

**Issue by jpmcarrilho** [alexmercerind/youtube-search-python#72]
Hello, I'm trying to run a CustomSearch with the subtitles filter `EgIoAQ%253D%253D`
[Youtube example](https://www.youtube.com/results?search_query=test&sp=EgIoAQ%253D%253D) (First result have subtitles, second dont)

```
customSearch = CustomSearch(query = 'test',searchPreferences = 'EgIoAQ%253D%253D',limit = 20)
```
But the results aren't subtitled. Am I doing something wrong?

**Comment by alexmercerind** [comment]
Hi there @jpmcarrilho !

I know what you are doing wrong. You need to "unescape" that string before passing.

i.e. "EgIoAQ%253D%253D" is actually "EgIoAQ%3D%3D".
