### ISSUE TITLE
Get Video Title and Keywords/Tags

### ISSUE THREAD

**Issue by susheelseth** [alexmercerind/youtube-search-python#76]
How to to get Video Title and Tags.

E.g. Input URL : https://www.youtube.com/watch?v=z0GKGpObgPY

Output
**Title -** Harry Styles - Sign of the Times (Audio) - YouTube
**Keywords -** sign of the times, harry styles sign of the times, harry styles, sign of the times audio, sing of the times, harry styles sign of the times audio, harry styles audio, sign of the times harry styles, signs of the times, sing of the times harry styles, sing of the times audio, sign of times, signs of the time, sign of the time, carolina, sign of the times lyrics, kiwi, meet me in the hallway, one direction, ed sheeran, taylor swift, official

**Comment by lodenrogue** [comment]
Where would the keywords come from? What's the source?

**Comment by susheelseth** [comment]
It would come from the video itself.. Source would be "og:tags:keyword". Something like this.

E.g. When you open any youtube video and then go to its view source then if you search for keyword then you'll see the keywords.

**Comment by lodenrogue** [comment]
I'm not seeing it. Can you show a screenshot for the video you linked above?

**Comment by alexmercerind** [comment]
Results from `Video.get` already contain keyword key in its map. Search results don't include.
