### ISSUE TITLE
Change the YouTube API key 

### ISSUE THREAD

**Issue by marcelosiqueira** [alexmercerind/youtube-search-python#77]
I need to make several queries, and the current API key has a limit, I tried to change the API key, but I couldn't, because all the keys I created were not accepted there is some way to change or use more keys.

**Comment by lodenrogue** [comment]
What is the limit?
Any way to externalize the API key?

**Comment by lodenrogue** [comment]
It seems the key is being stored here:
https://github.com/alexmercerind/youtube-search-python/blob/90d73a3efe992d238ea3623036e2ac3dc7f97169/youtubesearchpython/internal/constants.py#L24

**Comment by alexmercerind** [comment]
You can yourself assign custom key to that variable before calling any method or instantiating any object from the library.
I don't think that key ever runs out, its always the IP that gets banned.

**Comment by marcelosiqueira** [comment]
Yes, there is a quota for using the YouTube API!
https://developers.google.com/youtube/v3/getting-started#quota

The current key seems to renew this quota quickly, but I already had a problem when I do many searches, in my case it was when I tried to make more than 50 queries simultaneously.

I think about the solution of adding more keys or making it possible for a person to configure their personal key.

**Comment by alexmercerind** [comment]
@marcelosiqueira 
> Yes, there is a quota for using the YouTube API!

This project does NOT use YouTube API & that string is NOT YouTube Data API v3 key.
It is something that YouTube uses internally & it is being used by the people worldwide at this point & it never runs out.
