### ISSUE TITLE
search suggestions array will safe any suggestion, even if it doesnt fit the query

### ISSUE THREAD

**Issue by derOedipus** [alexmercerind/youtube-search-python#79]
When using search suggestion asynchron the internal array will be set once but wont be cleared for a new search suggestion. This results in an array which also returns search suggestions from previous querys, which have nothing to do with the current one. No idea if its intended or not, however if not the array creation needs to be moved in the get function.
![Screenshot from 2021-05-23 18-42-38](https://user-images.githubusercontent.com/84677587/119269217-d4b65480-bbf6-11eb-8070-715e658367d9.png)

**Comment by mytja** [comment]
Hello!
Thanks for your report
I have tested this, and it is true that it kept old search suggestions.
You can expect a PR soon.
Thank you
