### ISSUE TITLE
RuntimeWarning: coroutine 'main' was never awaited

### ISSUE THREAD

**Issue by plauthor** [alexmercerind/youtube-search-python#83]
Your code example produces this error:

videosResult = await videosSearch.next()
                  ^
SyntaxError: 'await' outside function

When inside a function then this error comes up:

RuntimeWarning: coroutine 'main' was never awaited
  main()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

What might be wrong please. Thank you.

**Comment by alexmercerind** [comment]
Learn to use Python. 
For reference, [asyncio](https://docs.python.org/3/library/asyncio.html).

**Comment by plauthor** [comment]
Use working examples.
