### ISSUE TITLE
Add timeout option

### ISSUE THREAD

**Issue by ricardofunke** [alexmercerind/youtube-search-python#88]
Sometimes I had an issue when getting to the next page search results with the VideosSearch.next() function where it just stays forever like something was wrong with the connection, so maybe it needs a connection timeout parameter

**Comment by mytja** [comment]
Async search already has a timeout, and i dont think sync one needs this...

Do you use async or sync version?

**Comment by ricardofunke** [comment]
I use the sync version, the problem is that sometimes it just hangs there forever so I had to implement a multiprocess function to force it to timeout.

**Comment by mytja** [comment]
Thanks for the comment.
I will add a timeout parametr soon...

**Comment by mytja** [comment]
Hello, @ricardofunke !
I have added timeout parameter. Let me know if it works :wink:

**Comment by ricardofunke** [comment]
Thanks mytja! I'll start using it and let you know, have a nice day! 🙂
