### ISSUE TITLE
Exception: Could not make request.

### ISSUE THREAD

**Issue by LipeBromf** [alexmercerind/youtube-search-python#90]
I made this very simple call just to test the library using python 3.8 in windos and it worked beautifully:

``` 
searchString = "any song here"
search = Search(searchString, limit=1)
print(search.result())
``` 

But, when I ran the same code in macOS big sur it returned me this error: Exception: Could not make request.
I can't think of any reasons as to why  this is happening...

**Comment by alexmercerind** [comment]
You might be helped by someone experienced the same problem on Mac OS.
https://github.com/alexmercerind/youtube-search-python/issues/65#issuecomment-865888284
