### ISSUE TITLE
what are the valid values for region?

### ISSUE THREAD

**Issue by brayo-pip** [alexmercerind/youtube-search-python#92]
I had 'KE' as my region but the video was still not available in my region making me think that maybe you have a certain format for specifying regions I don't know about.

**Comment by mytja** [comment]
Hello, @brayo-pip !
Thanks for the report.
Unfortunately YouTube makes a lot of changes to its site, so this might not work anymore... Your format is okay, KE stands for Kenya, and as far as I know the language spoken there is English, right?

First answer to these questions:
1. Is your video Unlisted on YouTube
2. Can you access this video on YouTube

May you send me the simple reproducible sample, and which video you are searching for?

**Comment by brayo-pip** [comment]
I resolved the problem... It wasn't from your library's end, thanks anyway
