### ISSUE TITLE
yt-dl update?

### ISSUE THREAD

**Issue by Zxce3** [alexmercerind/youtube-search-python#94]
I Make some telegram bot and use this for download yt song 
> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by alexmercerind** [comment]
We do not use youtube-dl in our source code anywhere.

**Comment by Zxce3** [comment]
> We do not use youtube-dl in our source code anywhere.

sorry my fault
