### ISSUE TITLE
Playlist information error

### ISSUE THREAD

**Issue by Shuvadip-Ghosh** [alexmercerind/youtube-search-python#96]
My code is 
from youtubesearchpython import *
playlist = Playlist.get('https://youtube.com/playlist?list=PLsXzm6mWVLb48IWXakRIIDnT6_Vb4yn27',mode = ResultMode.json)
print(playlist)
But this is throwing an error could not parse YouTube response 
Please can anyone help me out with this

**Comment by alexmercerind** [comment]
That's not even a playlist.
